### ISSUE TITLE
Response 400 every time

### ISSUE THREAD

**Issue by NickCassab** [CubieDev/TheNounProjectAPI#1]
Hi CubieDev,

I'm very glad that I found your wrapper for the nounprojectAPI! I love the noun project and I love API's !

I'm testing out a simple python script with your tool and unfortunately, I get a Response 400 error every time I send a request:

`Traceback (most recent call last):
  File "c:/Users/ngheta/Desktop/Personal/24-NounProject-MusicVideo/TheNounProjectAPI-master/TheNounProjectAPI-master/nick-testing.py", line 8, in <module>
    usage = api.get_usage()
  File "C:\Users\ngheta\AppData\Local\Programs\Python\Python38\lib\site-packages\wrapt\wrappers.py", line 602, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "c:\Users\ngheta\Desktop\Personal\24-NounProject-MusicVideo\TheNounProjectAPI-master\TheNounProjectAPI-master\TheNounProjectAPI\call.py", line 72, in wrapper
    raise STATUS_CODE_EXCEPTIONS[response.status_code](response)
TheNounProjectAPI.exceptions.BadRequest: Error with request <Response [400]>: Invalid parameters for request.`

I've double checked on the Noun Project website that my key and secret are correct and they are, I was even able to get a proper response using the example on their website when I manually give it the endpoint. Is it possible that they changed their API and this wrapper simply needs a quick update? Or am I missing something here:

`from TheNounProjectAPI import API`

`nounkey = "<my-noun-project-key>"`
`nounsecret = "<my-noun-project-secret>"`

`api = API(key= nounkey, secret= nounsecret)`

`usage = api.get_usage()`

`print(usage)`
`print("hello world")`

what do you think?

**Comment by tomaarsen** [comment]
Hello Nick,
I'm frustrated that my email has failed to notify me about this issue, so I've only just now seen this. My apologies.

I was able to run your sample program with my own key and secret with no issues. I'm unable to reproduce your issue. 
Perhaps you included the `<` and `>` in the string with your API key and secret? These should not be included in the strings. I'm at a loss of what else the problem could be.
